version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./:/app:delegated
    ports:
    - '8000:80'
    links:
    - mariadb
  mariadb:
    image: mariadb:10.1
    volumes:
    - mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Kiev"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'edge'
      MYSQL_PASSWORD: 'edge'
      MYSQL_DATABASE: 'edge'
    ports:
      - '3306:3306'
volumes:
  mariadb: